services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: dland
      POSTGRES_PASSWORD: dland
      POSTGRES_DB: dland
    ports:
      - "5432:5432"
    volumes:
      - dland_pg:/var/lib/postgresql/data

volumes:
  dland_pg:
