import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { env } from '../config/env';
import { sha256 } from '../utils/crypto';

/**
 * Private file storage for sensitive documents (title deeds, ID documents, payment receipts).
 *
 * Files are never reachable by a public URL. The API checks who may open a file, then issues a
 * short-lived signed link (see files.routes.ts). This local implementation keeps files on disk;
 * a cloud implementation (S3, R2…) only needs to provide the same three methods, with `signedUrl`
 * returning the provider's pre-signed URL.
 */
export interface PrivateStorage {
  /** Moves an uploaded temporary file into storage under `key`. */
  put(tempFilePath: string, key: string): Promise<void>;
  remove(key: string): Promise<void>;
  /** A link that opens the file until it expires. */
  signedUrl(key: string, ttlSeconds?: number): { url: string; expiresAt: Date };
}

export const PRIVATE_DIR = path.resolve(env.PRIVATE_STORAGE_DIR ?? path.join(__dirname, '../../storage/private'));
fs.mkdirSync(PRIVATE_DIR, { recursive: true });

// Keys are generated by us (timestamp + random hex + extension): nothing else is accepted,
// which also rules out path traversal when serving files.
const KEY_PATTERN = /^[a-z0-9-]+(\.[a-z0-9]{1,8})?$/;
export const isValidKey = (key: string) => KEY_PATTERN.test(key);

export function newKey(originalName: string) {
  const ext = path.extname(originalName).toLowerCase().replace(/[^a-z0-9.]/g, '').slice(0, 9);
  return `${Date.now()}-${crypto.randomBytes(12).toString('hex')}${ext}`;
}

const signingSecret = env.FILES_SIGNING_SECRET ?? sha256(`dland-files:${env.JWT_ACCESS_SECRET}`);

const signature = (key: string, expires: number) =>
  crypto.createHmac('sha256', signingSecret).update(`${key}:${expires}`).digest('hex');

/** Checks a link's signature and expiry (constant-time comparison). */
export function verifySignedLink(key: string, expires: number, sig: string) {
  if (!isValidKey(key) || !Number.isFinite(expires) || expires * 1000 < Date.now()) return false;
  const expected = Buffer.from(signature(key, expires), 'hex');
  const given = Buffer.from(sig, 'hex');
  return expected.length === given.length && crypto.timingSafeEqual(expected, given);
}

export const privateFilePath = (key: string) => path.join(PRIVATE_DIR, key);

export const localPrivateStorage: PrivateStorage = {
  async put(tempFilePath, key) {
    if (!isValidKey(key)) throw new Error(`Invalid storage key: ${key}`);
    await fs.promises.rename(tempFilePath, privateFilePath(key)).catch(async () => {
      // rename fails across drives: copy then delete.
      await fs.promises.copyFile(tempFilePath, privateFilePath(key));
      await fs.promises.unlink(tempFilePath);
    });
  },
  async remove(key) {
    if (!isValidKey(key)) return;
    await fs.promises.unlink(privateFilePath(key)).catch(() => undefined);
  },
  signedUrl(key, ttlSeconds = env.FILE_LINK_TTL_SECONDS) {
    const expires = Math.floor(Date.now() / 1000) + ttlSeconds;
    // Relative to the API: the app prefixes its API base URL.
    return { url: `/api/files/${key}?expires=${expires}&sig=${signature(key, expires)}`, expiresAt: new Date(expires * 1000) };
  },
};

export const privateStorage: PrivateStorage = localPrivateStorage;
